using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class enemyController : MonoBehaviour
{

	public Transform playerTransform;
	private Vector3 direction;
	static Animator anim2;
    // Start is called before the first frame update
    void Start()
    {
		anim2 = GetComponent<Animator>();
    }

    // Update is called once per frame
    void Update()
    {

		if (anim2.GetCurrentAnimatorStateInfo(0).IsName("fight_idle"))
		{
			direction = playerTransform.position - this.playerTransform.position;

			direction.y = 0;
			this.playerTransform.rotation = Quaternion.Slerp(this.transform.rotation, Quaternion.LookRotation(direction), 0.3f);
		}
    }
}
